'use client';

export default function TermsAndConditions() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 dark:from-slate-950 dark:to-slate-900 px-4 py-16">
      <div className="max-w-4xl mx-auto">
        <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-8 md:p-12 shadow-lg">
          <h1 className="text-4xl font-black mb-2 text-slate-900 dark:text-white">1HeroSocial Platform — Terms and Conditions</h1>
          <p className="text-sm text-slate-500 mb-1">Platform Usage Agreement</p>
          <p className="text-sm text-slate-500 mb-8">Effective Date: June 9, 2026</p>

          <div className="space-y-8 text-slate-700 dark:text-slate-300">
            <section>
              <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">1. Introduction &amp; Acceptance</h2>
              <p className="mb-3">These Terms and Conditions ("Terms") govern your access to and use of the 1HeroSocial platform, including all associated software, services, APIs, and content (collectively, the "Platform"). The Platform is operated by 1HeroSocial ("Company", "we", "us", or "our").</p>
              <p>By registering for an account, accessing, or using the Platform in any way, you ("Client", "Studio", "you") agree to be bound by these Terms. If you are accepting these Terms on behalf of a company or other legal entity, you represent that you have the authority to bind that entity. If you do not agree to these Terms, do not use the Platform.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">2. Definitions</h2>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>"Platform"</strong> means the 1HeroSocial software-as-a-service product, including all web interfaces, APIs, mobile applications, and related services.</li>
                <li><strong>"Studio"</strong> means a fitness studio, gym, or similar business that subscribes to the Platform.</li>
                <li><strong>"Vendor"</strong> means an entity that manages one or more Studios on the Platform.</li>
                <li><strong>"User"</strong> means any individual granted access to the Platform by a Studio or Vendor.</li>
                <li><strong>"Content"</strong> means any text, images, videos, data, or other material uploaded to or generated by the Platform.</li>
                <li><strong>"AI Services"</strong> means artificial intelligence-powered features including content generation, lead scoring, reply drafting, and campaign automation.</li>
                <li><strong>"Lead"</strong> means contact information and associated data for a prospective customer captured via the Platform.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">3. Account Registration &amp; Access</h2>
              <div className="space-y-4">
                <div>
                  <h3 className="text-lg font-semibold mb-2 text-slate-900 dark:text-white">3.1 Account Creation</h3>
                  <p>To use the Platform, you must register for an account by providing accurate, current, and complete information. You agree to update your information promptly if it changes. You are solely responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.</p>
                </div>
                <div>
                  <h3 className="text-lg font-semibold mb-2 text-slate-900 dark:text-white">3.2 Role-Based Access</h3>
                  <p>The Platform uses role-based access control. Each account is assigned a role (Super Admin, Studio Admin, Marketing Manager, Sales Agent, Trainer, Finance, or Customer) with corresponding permissions. You agree to access only those features and data that your role permits. Unauthorized access attempts may result in immediate account termination.</p>
                </div>
                <div>
                  <h3 className="text-lg font-semibold mb-2 text-slate-900 dark:text-white">3.3 Account Security</h3>
                  <p>You must immediately notify us at <a href="mailto:1herosocialai@gmail.com" className="text-blue-600 dark:text-blue-400 underline">1herosocialai@gmail.com</a> of any unauthorized use of your account or any security breach. We will not be liable for any loss or damage arising from your failure to comply with these security obligations.</p>
                </div>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">4. Use of the Platform</h2>
              <div className="space-y-4">
                <div>
                  <h3 className="text-lg font-semibold mb-2 text-slate-900 dark:text-white">4.1 Permitted Use</h3>
                  <p>Subject to these Terms and payment of applicable fees, we grant you a limited, non-exclusive, non-transferable, revocable licence to access and use the Platform solely for your internal business operations in managing your fitness studio(s).</p>
                </div>
                <div>
                  <h3 className="text-lg font-semibold mb-2 text-slate-900 dark:text-white">4.2 Prohibited Conduct</h3>
                  <p className="mb-3">You agree NOT to:</p>
                  <ul className="list-disc pl-6 space-y-1">
                    <li>Use the Platform for any unlawful purpose or in violation of any applicable law or regulation.</li>
                    <li>Attempt to gain unauthorized access to any part of the Platform or any connected systems.</li>
                    <li>Reverse engineer, decompile, disassemble, or otherwise attempt to derive the source code of the Platform.</li>
                    <li>Use the Platform to transmit spam, malware, or other harmful content.</li>
                    <li>Scrape, crawl, or otherwise extract data from the Platform without our prior written consent.</li>
                    <li>Resell, sublicense, or otherwise provide access to the Platform to any third party without our written authorization.</li>
                    <li>Use the AI Services to generate content that is defamatory, discriminatory, misleading, or violates third-party intellectual property rights.</li>
                    <li>Interfere with or disrupt the integrity or performance of the Platform or its underlying infrastructure.</li>
                  </ul>
                </div>
                <div>
                  <h3 className="text-lg font-semibold mb-2 text-slate-900 dark:text-white">4.3 AI-Generated Content</h3>
                  <p className="mb-3">The Platform includes AI Services that generate marketing content, lead responses, campaign copy, and other materials. You acknowledge and agree that:</p>
                  <ul className="list-disc pl-6 space-y-1">
                    <li>You are solely responsible for reviewing, approving, and publishing any AI-generated content before it goes live.</li>
                    <li>We do not guarantee the accuracy, completeness, or suitability of AI-generated content for your specific use case.</li>
                    <li>AI-generated content does not constitute legal, financial, medical, or professional advice.</li>
                    <li>You retain full responsibility for compliance with advertising standards, consumer protection laws, and platform policies (Meta, TikTok, Google Ads, etc.) for any content you publish.</li>
                  </ul>
                </div>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">5. Multi-Tenant Architecture &amp; Data Isolation</h2>
              <p>The Platform operates as a multi-tenant system. Each Studio's data is logically isolated using row-level security controls. We implement commercially reasonable technical measures to prevent cross-tenant data access. However, you acknowledge that no system is completely impenetrable and agree not to hold us liable for breaches resulting from sophisticated attacks beyond our reasonable control.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">6. Third-Party Integrations</h2>
              <p className="mb-3">The Platform integrates with third-party services including Meta WhatsApp, Google Sheets, Meta Ads, TikTok, and Google Ads (collectively, "Third-Party Services"). You acknowledge that:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Use of Third-Party Services is subject to those providers' own terms of service and privacy policies.</li>
                <li>We are not responsible for the availability, accuracy, or performance of Third-Party Services.</li>
                <li>You are solely responsible for obtaining all necessary consents, licences, and permissions required to use Third-Party Services in connection with the Platform.</li>
                <li>We may modify or discontinue integrations with Third-Party Services at any time with reasonable notice.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">7. Intellectual Property</h2>
              <div className="space-y-4">
                <div>
                  <h3 className="text-lg font-semibold mb-2 text-slate-900 dark:text-white">7.1 Our IP</h3>
                  <p>The Platform, including all software, algorithms, AI models, design, trademarks, and documentation, is owned by 1HeroSocial or its licensors and is protected by intellectual property laws. Nothing in these Terms grants you any right, title, or interest in the Platform except the limited licence set out in Section 4.1.</p>
                </div>
                <div>
                  <h3 className="text-lg font-semibold mb-2 text-slate-900 dark:text-white">7.2 Your Content</h3>
                  <p>You retain ownership of all Content you upload to the Platform. By uploading Content, you grant us a worldwide, royalty-free, non-exclusive licence to use, store, process, and display your Content solely as necessary to provide the Platform services to you.</p>
                </div>
                <div>
                  <h3 className="text-lg font-semibold mb-2 text-slate-900 dark:text-white">7.3 Feedback</h3>
                  <p>If you provide us with feedback, suggestions, or ideas regarding the Platform, you grant us an irrevocable, royalty-free licence to use such feedback for any purpose without obligation to you.</p>
                </div>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">8. Confidentiality</h2>
              <p>Each party agrees to keep the other's Confidential Information strictly confidential and not to disclose it to any third party without prior written consent, except as required by law. "Confidential Information" includes, but is not limited to, business plans, customer data, technical specifications, pricing, and API keys. This obligation survives termination of these Terms for a period of five (5) years.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">9. Warranties &amp; Disclaimers</h2>
              <p className="mb-3 font-semibold">THE PLATFORM IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR UNINTERRUPTED OPERATION.</p>
              <p>We do not warrant that: (a) the Platform will be error-free or uninterrupted; (b) AI-generated content will be accurate or suitable; (c) results obtained from the Platform will meet your expectations; or (d) Third-Party Services will function as expected.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">10. Limitation of Liability</h2>
              <p className="mb-3 font-semibold">TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL 1HEROSOCIAL, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, LOSS OF DATA, OR BUSINESS INTERRUPTION, ARISING OUT OF OR RELATED TO YOUR USE OF THE PLATFORM, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
              <p>OUR AGGREGATE LIABILITY FOR ALL CLAIMS ARISING OUT OF OR RELATED TO THESE TERMS SHALL NOT EXCEED THE TOTAL FEES PAID BY YOU TO US IN THE THREE (3) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">11. Indemnification</h2>
              <p>You agree to indemnify, defend, and hold harmless 1HeroSocial and its affiliates, officers, directors, employees, and agents from and against any claims, liabilities, damages, judgments, awards, losses, costs, and expenses (including reasonable legal fees) arising out of or relating to: (a) your violation of these Terms; (b) your Content; (c) your use of the Platform; (d) your violation of any third-party rights; or (e) any content published via the Platform at your direction.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">12. Term &amp; Termination</h2>
              <div className="space-y-4">
                <div>
                  <h3 className="text-lg font-semibold mb-2 text-slate-900 dark:text-white">12.1 Term</h3>
                  <p>These Terms commence on the date you first access the Platform and continue until terminated.</p>
                </div>
                <div>
                  <h3 className="text-lg font-semibold mb-2 text-slate-900 dark:text-white">12.2 Termination by You</h3>
                  <p>You may terminate your subscription at any time through your account settings or by contacting us. Termination takes effect at the end of your current billing period. No refunds will be issued for unused portions of a billing period unless required by law.</p>
                </div>
                <div>
                  <h3 className="text-lg font-semibold mb-2 text-slate-900 dark:text-white">12.3 Termination by Us</h3>
                  <p>We may suspend or terminate your access immediately, with or without notice, if: (a) you breach these Terms; (b) we reasonably suspect fraudulent activity; (c) required by law; or (d) continued service poses a security or legal risk. We may also terminate with 30 days' written notice for any other reason.</p>
                </div>
                <div>
                  <h3 className="text-lg font-semibold mb-2 text-slate-900 dark:text-white">12.4 Effect of Termination</h3>
                  <p>Upon termination: (a) your licence to use the Platform immediately ceases; (b) you must cease all use of the Platform; (c) we will make your data available for export for 30 days following termination; (d) after 30 days, we may permanently delete your data.</p>
                </div>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">13. Governing Law &amp; Disputes</h2>
              <p>These Terms are governed by and construed in accordance with applicable law. Any dispute arising from these Terms shall first be attempted to be resolved through good-faith negotiation. If unresolved within 30 days, disputes shall be submitted to binding arbitration.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">14. Modifications to Terms</h2>
              <p>We reserve the right to modify these Terms at any time. We will notify you of material changes by email and/or by posting a notice on the Platform at least 14 days before the changes take effect. Your continued use of the Platform after the effective date constitutes acceptance of the revised Terms.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4 text-slate-900 dark:text-white">15. Miscellaneous</h2>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Entire Agreement:</strong> These Terms, together with the Privacy Policy and Payment Terms, constitute the entire agreement between you and us regarding the Platform.</li>
                <li><strong>Severability:</strong> If any provision is held invalid or unenforceable, the remaining provisions continue in full force.</li>
                <li><strong>No Waiver:</strong> Failure to enforce any provision does not constitute a waiver of our right to enforce it in the future.</li>
                <li><strong>Assignment:</strong> You may not assign your rights under these Terms without our prior written consent. We may assign our rights freely.</li>
                <li><strong>Contact:</strong> For questions about these Terms, contact us at <a href="mailto:1herosocialai@gmail.com" className="text-blue-600 dark:text-blue-400 underline">1herosocialai@gmail.com</a>.</li>
              </ul>
            </section>

            <section className="bg-blue-50 dark:bg-blue-950/30 border border-blue-200 dark:border-blue-800 rounded-lg p-6">
              <h3 className="text-lg font-bold text-slate-900 dark:text-white mb-3">Questions About These Terms?</h3>
              <p><strong>Email:</strong> <a href="mailto:1herosocialai@gmail.com" className="text-blue-600 dark:text-blue-400 underline">1herosocialai@gmail.com</a></p>
            </section>
          </div>
        </div>
      </div>
    </main>
  );
}
